### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TarikHuber** [aabedraba/nodejs-chat-server#1]
This is not working :( can you help me?

**Comment by aabedraba** [comment]
Why you bothering me?

**Comment by aabedraba** [comment]
What's your problem @TarikHuber

**Comment by TarikHuber** [comment]
It's just not working. Can you help me? Why is this not working on my device -.-

**Comment by aabedraba** [comment]
Send error message you prick

**Comment by TarikHuber** [comment]
I get Page Not Found when I try to find a solution on https://www.gooooooogle.com/

**Comment by TarikHuber** [comment]
It's still not working

**Comment by aabedraba** [comment]
Can't help you mate, go do something else, maybe go outside. 
Closing issue.

**Comment by TarikHuber** [comment]
Now I have another isse -.-

**Comment by aabedraba** [comment]
https://www.mentalhelp.net/

**Comment by TarikHuber** [comment]
Again Brain Not Found -.-
